### PR TITLE
[Android][Crash] Add check on keys

### PR DESCRIPTION
**Pull request by Soliman13**
App is crashing at Tealium initialisation when we don't provide some properties on TealiumConfig object.
1st issue: We are trying to get the KEY_CONFIG_MODULES key from TealiumConfig properties, however we can't give this key... That causes a crash.
2nd issue:
As we can see, even if the **return value is @Nullable**, the **param values** of getString(), getArray() ... methods is @NonNull. That causes a crash.

Screenshot 2021-03-01 at 10 05 44

I added presence checks on all optional keys to ensure that there will no crash

### CODE REVIEW

**Comment by jameskeith** [comment]
Hi @Soliman13
Is it possible to get an actual stacktrace for the crashes that you are seeing? and perhaps the configuration code that you have used when instantiating the Tealium modules?

The sample application on this repository also does not supply a `modules` key either, as it is only reserved for future usage and so not defined on the `TealiumConfig` type definition - you shouldn't need to supply it.
As discussed on the other pull request, although the parameters are marked a `@NonNull` we are not supplying any `null` values to these methods; they are string constants defined elsewhere in the project.
Similarly, the return types are marked as `@Nullable` and we are safely checking this using kotlin's `?.` safe nullable check before using the value returned.

I cannot reproduce any crashes by omitting configuration, so i think we need more information about your setup.

**Comment by Soliman13** [comment]
Hello @jameskeith 

I get what you say, if these values are never null it couldn't crash... but there is probably something wrong here, as with this config:

Screenshot 2021-03-03 at 13 32 37

I get the following issue:

Screenshot 2021-03-03 at 13 35 07

Screenshot 2021-03-03 at 13 40 24

**Comment by jameskeith** [comment]
Thanks @Soliman13 
I've found the cause of the problem - looks like the behaviour was changed somewhere between [v0.62](https://github.com/facebook/react-native/blob/0.62-stable/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java#L123) and [v0.63](https://github.com/facebook/react-native/blob/0.63-stable/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java#L123) of React Native.
I'm guessing you're using 0.62.x or below?

Given the impact of this, we'll need a few other extra checks as for some of the other keys too as well as test coverage; so I'll be raising this internally to get this addressed.
Thanks for raising the issue with us.

**Comment by Soliman13** [comment]
Thanks for your reactivity, @jameskeith 

I am using RN 0.63.3.

**Comment by jameskeith** [comment]
interesting @Soliman13 - thanks for the info

Our test app in this repo uses 0.63.4 and works as expected, so I've just set it to use 0.63.3 and can indeed replicate the same problem - and stepping through the code, I can see that `NoSuchKeyException` is thrown on 0.63.3, where it isn't in 0.63.4. So i guess it must have been that version that the change was made. 
It also seems that the labels on the `react-native` repo don't necessarily reflect the underlying version of the code (they do only have one label per minor release, so i assume that actually refers to the latest build of that minor release)

In any case, if you're able to update to 0.63.4 then this should be resolved whilst we push through a fix from our end.

**Comment by Soliman13** [comment]
Hi @jameskeith 

Indeed, update to 0.63.4 solves the issue.

Thanks!

**Comment by Soliman13** [comment]
Hi @jameskeith ;

When updating RN to 0.63.4, I have no data sent from iOS.

**Comment by jameskeith** [comment]
Hi @Soliman13 
great to hear that 0.63.4 solved the issue on Android; obviously not so great to hear about iOS.

Do you have any log output you could share from iOS? Typically it is likely to be one of the DispatchValidators that will be queuing up your events - for example, I can see that your code initially sets `gdpr` as your consent policy, so you would need to grant consent before any events left the device.
The log output on the device should specify why any particular events were queued.

**Comment by Soliman13** [comment]
Turning CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES to YES solved the issue.

That's strange we have to do that for such a 'minor' RN release

**Comment by jameskeith** [comment]
@Soliman13
thanks for the information; that sounds familiar actually.
great to hear it's all working now - please let us know if you have any further issues.

**Comment by jameskeith** [comment]
fixed in release v2.0.3 - closing.
please let us know if you still have any further issues

**Pull request closed without merging**
